// Package keystore implements optional at-rest encryption for the local
// YAML provider: a standard age (age-encryption.org/v1) envelope stored in
// place of plaintext secrets, key-material resolution (env → OS keyring →
// interactive passphrase), and StatusOf for reporting encryption state.
//
// Envelope format: the payload (the same YAML shape as a plaintext local
// file — version, secrets, meta) is encrypted as one age file, so it
// decrypts with the external age/rage CLIs, not just with skret. The
// recipient is an age X25519 keypair when the key material is an age
// private key (AGE-SECRET-KEY-1...), or an age scrypt recipient derived
// from the passphrase otherwise. Legacy skret-encrypted-v1 files are still
// read (and written back unchanged until migration) — see legacy.go.
package keystore

import (
	"bytes"
	"fmt"
	"io"

	"filippo.io/age"
	"gopkg.in/yaml.v3"
)

// Format is the age wire-format magic line. Its presence at the start of an
// on-disk file is how the file is recognized as encrypted, independent of
// any config flag; it is also the format string reported by StatusOf.
const Format = "age-encryption.org/v1"

// EnvKeyPrimary / EnvKeyFallback are the environment variables consulted for
// key material, in order. SKRET_AGE_KEY wins so the name stays stable.
const (
	EnvKeyPrimary  = "SKRET_AGE_KEY"
	EnvKeyFallback = "SKRET_LOCAL_KEY"
)

// KeyringService / KeyringUser identify the OS keyring entry holding the
// generated age identity (service "skret" matches internal/auth).
const (
	KeyringService = "skret"
	KeyringUser    = "local-enc-key"
)

// payload is the age-encrypted plaintext: exactly the plaintext local-file
// shape, so external `age -d` output is a normal skret secrets file.
type payload struct {
	Version string            `yaml:"version"`
	Secrets map[string]string `yaml:"secrets"`
	Meta    map[string]string `yaml:"meta,omitempty"`
}

// Detect reports whether raw looks like a standard age file. It never
// errors: unknown bytes are simply "not encrypted".
func Detect(raw []byte) bool {
	return bytes.HasPrefix(raw, []byte(Format))
}

// ParseIdentity parses an age X25519 private key ("AGE-SECRET-KEY-1...").
func ParseIdentity(s string) (*age.X25519Identity, error) {
	id, err := age.ParseX25519Identity(s)
	if err != nil {
		return nil, newError(CodeValidationError,
			fmt.Sprintf("keys: %s must be an age private key (AGE-SECRET-KEY-1..., as generated by age-keygen or `skret keys init`)", EnvKeyPrimary), err)
	}
	return id, nil
}

// GenerateIdentity returns a fresh age X25519 private key in bech32 form
// (AGE-SECRET-KEY-1...) — the value stored in the OS keyring by
// `skret keys init`.
func GenerateIdentity() (string, error) {
	id, err := age.GenerateX25519Identity()
	if err != nil {
		return "", newError(CodeGenericError, "keys: generate age identity", err)
	}
	return id.String(), nil
}

// recipientFor maps key material to an age recipient: an X25519 public key
// when the material is an age key (private AGE-SECRET-KEY-1... or public
// age1...), otherwise an age scrypt recipient derived from the material as
// a passphrase.
func recipientFor(material string) (age.Recipient, error) {
	if id, err := age.ParseX25519Identity(material); err == nil {
		return id.Recipient(), nil
	}
	if rec, err := age.ParseX25519Recipient(material); err == nil {
		return rec, nil
	}
	rec, err := age.NewScryptRecipient(material)
	if err != nil {
		return nil, newError(CodeValidationError, "keys: build encryption recipient", err)
	}
	return rec, nil
}

// identityFor maps key material to an age identity: an X25519 identity when
// the material is an age private key, otherwise an age scrypt identity
// derived from the material as a passphrase.
func identityFor(material string) (age.Identity, error) {
	if id, err := age.ParseX25519Identity(material); err == nil {
		return id, nil
	}
	id, err := age.NewScryptIdentity(material)
	if err != nil {
		return nil, newError(CodeValidationError, "keys: build decryption identity", err)
	}
	return id, nil
}

// Seal encrypts secrets into an age envelope using keyMaterial (an age
// private key, an age public key, or a passphrase — see recipientFor).
func Seal(secrets map[string]string, keyMaterial string) ([]byte, error) {
	return SealWithMeta(secrets, nil, keyMaterial)
}

// SealWithMeta is Seal plus per-key metadata stored inside the encrypted
// payload. A nil/empty meta produces the same format (the meta section is
// simply omitted).
func SealWithMeta(secrets map[string]string, meta map[string]string, keyMaterial string) ([]byte, error) {
	if keyMaterial == "" {
		return nil, newError(CodeValidationError, "keystore: key material is empty", nil)
	}
	rec, err := recipientFor(keyMaterial)
	if err != nil {
		return nil, err
	}
	plaintext, err := yaml.Marshal(&payload{Version: "1", Secrets: secrets, Meta: meta})
	if err != nil {
		return nil, newError(CodeGenericError, "keystore: marshal payload", err)
	}
	var buf bytes.Buffer
	w, err := age.Encrypt(&buf, rec)
	if err != nil {
		return nil, newError(CodeGenericError, "keystore: open age envelope", err)
	}
	if _, err := w.Write(plaintext); err != nil {
		return nil, newError(CodeGenericError, "keystore: write age payload", err)
	}
	if err := w.Close(); err != nil {
		return nil, newError(CodeGenericError, "keystore: close age envelope", err)
	}
	return buf.Bytes(), nil
}

// Open decrypts an age envelope previously written by Seal. Wrong key
// material or tampered bytes return an AuthError carrying an actionable
// hint.
func Open(raw []byte, keyMaterial string) (map[string]string, error) {
	secrets, _, err := OpenWithMeta(raw, keyMaterial)
	return secrets, err
}

// OpenWithMeta is Open plus the payload's per-key metadata map (nil when
// the envelope carries none).
func OpenWithMeta(raw []byte, keyMaterial string) (map[string]string, map[string]string, error) {
	if keyMaterial == "" {
		return nil, nil, newError(CodeValidationError, "keystore: key material is empty", nil)
	}
	id, err := identityFor(keyMaterial)
	if err != nil {
		return nil, nil, err
	}
	r, err := age.Decrypt(bytes.NewReader(raw), id)
	if err != nil {
		return nil, nil, withRemediation(newError(CodeAuthError,
			"keystore: decrypt failed (wrong key material or tampered file)", err),
			"verify SKRET_AGE_KEY matches the key created by `skret keys init` (AGE-SECRET-KEY-1...)")
	}
	plaintext, err := io.ReadAll(r)
	if err != nil {
		// Payload chunks authenticate during streaming: a corrupted payload
		// is the same contract as a wrong key — exit 4, never a partial read.
		return nil, nil, withRemediation(newError(CodeAuthError,
			"keystore: decrypt failed (wrong key material or tampered file)", err),
			"verify SKRET_AGE_KEY matches the key created by `skret keys init` (AGE-SECRET-KEY-1...)")
	}
	var p payload
	if err := yaml.Unmarshal(plaintext, &p); err != nil {
		return nil, nil, newError(CodeConfigError, "keystore: parse age payload", err)
	}
	if p.Secrets == nil {
		p.Secrets = map[string]string{}
	}
	return p.Secrets, p.Meta, nil
}

// StanzaKind reports the age recipient stanza type of a detected age file
// ("scrypt" or "X25519"), scanned from the textual header. It is display
// metadata for StatusOf, never a parse of ciphertext.
func StanzaKind(raw []byte) string {
	header := raw
	if i := bytes.Index(raw, []byte("\n--- ")); i >= 0 {
		header = raw[:i]
	}
	switch {
	case bytes.Contains(header, []byte("\n-> scrypt ")):
		return "scrypt"
	case bytes.Contains(header, []byte("\n-> X25519 ")):
		return "X25519"
	default:
		return "unknown"
	}
}

// RecipientKind reports which age recipient the key material maps to:
// "X25519" for age keys (AGE-SECRET-KEY-1... / age1...), "scrypt" for the
// passphrase arm.
func RecipientKind(material string) string {
	if _, err := age.ParseX25519Identity(material); err == nil {
		return "X25519"
	}
	if _, err := age.ParseX25519Recipient(material); err == nil {
		return "X25519"
	}
	return "scrypt"
}
