repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.0
    hooks:
      - id: golangci-lint
        args: ["--fix"]

  - repo: local
    hooks:
      - id: gofumpt
        name: gofumpt
        entry: gofumpt -w
        language: system
        types: [go]
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix]
